# Site settings
title: Tim Nicholls
email: timcnicholls@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my test Github pages site using Jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://timcnicholls.github.io" # the base hostname & protocol for your site
twitter_username: timcnicholls
github_username:  timcnicholls

# Build settings
markdown: kramdown
